### PR TITLE
Query account

### PR DESCRIPTION
**Pull request by MartinEvandt**
Based off of  "Get user-related machines" and "Get machine logon users" from Microsoft Defender for Endpoint's API
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-user-related-machines
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machine-log-on-users

Conformance clauses not added.

### CODE REVIEW

**Comment by dlemire60** [comment]
In section 2.3.1.2, the PR has the following regarding `query edr:account` (lines 600-602):

> - where the account Target Type is not empty and an Actuator Specifier is not set
>   - MUST respond with status code 200
>   - MUST return _a list of all endpoints the account exists on_ in the results (emphasis added)
 
If you are querying the EDR actuator on a single endpoint, how is it supposed to know about / respond with "all endpoints" where the account exists? Wouldn't that EDR only know accounts that exist on the endpoint where the EDR is operating? I don't question the value of the information, but I'm uncertain any individual endpoint's EDR actuator can provide the desired information.

**Comment by MartinEvandt** [comment]
@dlemire60 The intention is that when a specific endpoint/host is _not_ specified, the query returns all the hosts the user account has logged on to. 

The Actuator Specifier of the query Action should be the central management server of the EDR, which is not properly defined in the AP. The specifiers were added very early in the project and is way overdue a revisit.

**Comment by MartinEvandt** [comment]
Here's a rough sketch of how I see it in my head. By account not being specified I mean that none of the account Target's fields are populated. I will have a PR with updated Actuator Specifiers ready by the next TC meeting, and update this PR to reflect the changes.

Untitled Diagram (1)

**Comment by Vasileios-Mavroeidis** [comment]
Are the illustrations correct? I think no matter what you request the commands should go to the server. How the server performs the actions is not our concern.

@dlemire60 i think that my comment also answers your question

**Comment by MartinEvandt** [comment]
Yes, all commands have to go to the server (after which they may or may not be sent to an agent, which as you say is not our concern), this was just meant to illustrate that I am sometimes asking for data from a specific machine/agent, and other times from all machines/agents managed by the server.

**Comment by Vasileios-Mavroeidis** [comment]
So maybe use the server icons then and improve the language to reflect your point. The way it looks now a server communicates with the EDR agents using OpenC2.

That's a nice use case though. The next level of OpenC2 implementation / intra-technology implementations (new term invented)

**Comment by dlemire60** [comment]
(sorry to have dropped the conversation)  

I guess I needed to have checked my assumptions at the door.  😃  I've been implicitly reading "EDR" as "EDR agent", so in my mind the Consumers were located on individual endpoints, whereas your thinking is that the Consumer is the EDR (management?) server. That certainly lends a very different perspective on what information can be expected to be available. And answers my original question.

EDIT: Looking over the current draft I see it still have most of the Section 1 boilerplate we created and used for the original three specs. At this point our working assumption is that we don't need that any more.  I think there's an opportunity here to envision a new Section 1 "template" for actuator profiles and use it to clearly define the scope and context for the AP, something at least somewhat similar to the Operating Model sections of the two transfer specifications.

**Pull request closed without merging**
