### PR TITLE
Downstream devices

### PR DESCRIPTION
**Pull request by MartinEvandt**
1. Contains fields 'devices' and 'device_groups'
    1. Both fields are arrays. Felt redundant to have a third field specifying one and only one device
3. Have not included a 'selector' field such as the one shown in the draft in #31
    1. Will implement in later versions once such operations are defined in the planned Endpoints Analytics AP 
4. Defined which Commands MUST implement downstream devices
5. All Commands MAY implement downstream devices
    1. E.g., for 'contain device' aimed at multiple devices/groups ([Example from Palo Alto](https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/response-actions/isolate-endpoints)), 
    2. Does this need to be addressed? Something like a clause that the 'device' fields must be left empty when using downstream_device for Action/Target pairs where the Target is of type device?

### CODE REVIEW

**Comment by MartinEvandt** [comment]
Note that a tenant_id Actuator Specifier was added in PR #48

**Comment by MartinEvandt** [comment]
A list of all Commands which MUST implement downstream devices as an arg can be seen here: https://github.com/oasis-tcs/openc2-ap-er/pull/49/files#diff-db51f9290fea21b2fb253aa5a478fd0c6343c540ba1fd2f5e873753620d41250R1157

**Comment by Vasileios-Mavroeidis** [comment]
I think we concluded that actuator refers to a profile. So the specifiers need to be removed. Hostname is addressed already within a message. Can we include the tenant id in the arguments? Something like "downstream_manager". I'm reviewing this from my phone. I'll take a look again in detail the next days. -V

**Comment by Vasileios-Mavroeidis** [comment]
@davaya any comments ?

**Pull request merged**
